### ISSUE TITLE
B0050 Incomplete

### ISSUE THREAD

**Issue by JeffCimminoAmericanSurplus** [AmericanSurplusInc/Product-Pages#17]
1. Meta description needed for page
2. Add new yard ramps as a related product

The rest of these issues are just with presentation in product.xml, but it's important that our data is properly formatted (we're doing this with XML so that it's machine readable in the event we ever need to import this stuff into salesforce. If the data's malformed here, it won't import properly.) I already made changes so be sure to pull the branch before you make more changes:

3. Attributes should be formatted such that each attribute gets it's own <attribute> section, see this sample from Crown 20M Stackers:
```` xml
<attributes>
 <attribute>
  <name>Brand</name>
  <value>Crown</value>
 </attribute>
 <attribute>
  <name>Model</name>
  <value>20M</value>
 </attribute>
 ...
 <attribute>
  <name>NMFC Code</name>
  <value>189240</value>
 </attribute>
</attributes>
````

4. Fill out the `<images>` section with the metadata about each image. See this example from Crown 20M Stackers:
```` xml
<images> <!-- Include all pictures on the page, in both gallery and body. -->
 <image>
  <name>Crown20MWalkBehindStacker.png</name>
  <placement>gallery</placement> <!-- gallery or body -->
  <is-primary>1</is-primary> <!-- 1 = true, 0 = false, blank on body pictures -->
  <priority>1</priority> <!-- blank on body pictures -->
  <alt>Used Crown 20M Walk-Behind Electric Stackers</alt>
 </image>
 ...
</images>
````
Like the attributes section, each image gets it's own `<image>` section inside the `<images>` tag. Imagine these tags as if they're divs, the nesting matters just the same.

5. I already filled out the title, meta title, product code, pricing, category, and site presence sections. Keep in mind in the future that everything in these xml files should mirror the site exactly, as that's the only way these will be of any use to us.

**Comment by jberg418** [comment]
all set changes are made
