### ISSUE TITLE
Get Picture of Beam Assembly machine

### ISSUE THREAD

**Issue by JeffCimminoAmericanSurplus** [AmericanSurplusInc/Product-Pages#59]
Both action shots and stills would be useful.

This will be used for a "Custom sized pallet rack beams" page.

**Comment by JeffCimminoAmericanSurplus** [comment]
If anyone is going to know anything about where it is, I'd refer to Pete in Rack.

**Comment by jberg418** [comment]
complete

**Comment by jberg418** [comment]
complete
