### ISSUE TITLE
Changes in Box Locker Category

### ISSUE THREAD

**Issue by JeffCimminoAmericanSurplus** [AmericanSurplusInc/Product-Pages#62]
For both products: 
Change _Locker $dimension_ attributes to their respective regular depth, width, and height attributes.
This locker https://www.americansurplus.com/used-12-wide-box-lockers.html Should be "Used 10" Wide Box Lockers"

**Comment by JeffCimminoAmericanSurplus** [comment]
Do this quickly as well:
Cut out the picture on this page: https://www.americansurplus.com/used-box-lockers-12-wide.html, flip it over so its sitting upright, and set it as primary for that page.

**Comment by jberg418** [comment]
all set
